### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by victorup** [eaclark07/engen#1]
Hello, 
I' m very interested in this paper. But I couldn't understand c++. Do you have the code of Python version？
Thank you!

**Comment by eaclark07** [comment]
Sorry, there's no Python version at this time.

**Comment by jiyfeng** [comment]
Hi, I have a student implementing the model in Python/Pytorch and hopefully we can get it done soon.

**Comment by victorup** [comment]
That's great! Thank you.

**Comment by victorup** [comment]
> Hi, I have a student implementing the model in Python/Pytorch and hopefully we can get it done soon.

Hello, is the Pytorch code available? Thanks for your implementation.

**Comment by victorup** [comment]
Hello, how to recognize the entities in sentences? Do entities need to be extracted from sentences first? And how to select whether to generate the mentioned entity or not or general words?

**Comment by eaclark07** [comment]
Yes, we trained on data that was already annotated with entity information. When we ran it, we used Stanford CoreNLP to annotate the data with information about whether the word referred to an entity, and if so which entity. When we generate text, we predict this same entity information as well (e.g., whether the word refers to an entity).

**Comment by victorup** [comment]
![image](https://user-images.githubusercontent.com/44796817/85347594-98ccc800-b52b-11ea-8152-614d4e77099a.png)

Excuse me, here I have some questions. 
1. What is the representation of **e** in equal(3)? Is it an index of the entity? How to initialize the **W_entity**. 
2. What is **f(i)**? 
3. What is the vector in "**its vector** is assigned to e_current"?

Thank you so much!

**Comment by victorup** [comment]
> Hi, I have a student implementing the model in Python/Pytorch and hopefully we can get it done soon.

Thanks for your implementation. Is the Pytorch code available?
